name: Create .env from GitHub Secrets

on:
  push:
    branches:
      - master

jobs:
  create-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Secrets are available
        run: |
          if [ -z "${{ secrets.DB_PASSWORD }}" ]; then
            echo "DB_PASSWORD is missing!"
            exit 1
          fi
          if [ -z "${{ secrets.DB_HOST }}" ]; then
            echo "DB_HOST is missing!"
            exit 1
          fi
          if [ -z "${{ secrets.DB_NAME }}" ]; then
            echo "DB_NAME is missing!"
            exit 1
          fi
          echo "All required secrets are available!"

      - name: Create .env file from GitHub Secrets
        run: |
          DB_USER="postgres"
          DB_HOST="${{ secrets.DB_HOST }}"
          DB_NAME="${{ secrets.DB_NAME }}"
          DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          DB_PORT="5432"  # Cổng mặc định của PostgreSQL

          DATABASE_POSTGRES_URL="postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME"

          # Tạo file .env
          echo "DATABASE_POSTGRES_URL=$DATABASE_POSTGRES_URL" > .env
          echo ".env file has been created successfully!"

      - name: Verify .env file
        run: cat .env
