name: Create .env from GitHub Secrets

on:
  push:
    branches:
      - master

jobs:
  create-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Secrets are available
        run: |
          REQUIRED_SECRETS=("DB_PASSWORD" "DB_HOST" "DB_NAME")
          for SECRET in "${REQUIRED_SECRETS[@]}"; do
            if [ -z "${{ secrets[$SECRET] }}" ]; then
              echo "$SECRET is missing!"
              exit 1
            fi
          done
          echo "All required secrets are available!"

      - name: Create .env file from GitHub Secrets
        run: |
          DB_USER="postgres"
          DB_HOST="${{ secrets.DB_HOST }}"
          DB_NAME="${{ secrets.DB_NAME }}"
          DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          DB_PORT="5432"

          DATABASE_POSTGRES_URL="postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME"

          # Tạo file .env
          echo "DATABASE_POSTGRES_URL=$DATABASE_POSTGRES_URL" > .env

      - name: Verify .env file
        run: cat .env
