name: Create .env from GitHub Secrets

on:
  push:
    branches:
      - master

jobs:
  create-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Secrets are available
        run: |
          REQUIRED_SECRETS=("DB_PASSWORD" "DB_HOST" "DB_NAME")
          for SECRET in "${REQUIRED_SECRETS[@]}"; do
            if [ -z "${{ secrets[$SECRET] }}" ]; then
              echo "$SECRET is missing!"
              exit 1
            fi
          done
          echo "All required secrets are available!"

      - name: Set environment variables for setup.sh
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV

      - name: Run setup.sh to create .env file
        run: |
          chmod +x ./setup.sh
          ./setup.sh
